app/cms/__init__.py
from flask import Blueprint

cms = Blueprint('cms',__name__,
                 template_folder='templates',
                 static_folder='static')
from . import routes

app/cms/routes.py
from flask import render_template,request,redirect,url_for
from flask_mysqldb import MySQL 
from . import cms
from app import db

def com():
    com = db.connection.commit()
    return com

def cur():
    cur = db.connection.cursor()
    return cur

def deleteRow(id,table,field):
    cur().execute('DELETE FROM '+table+' WHERE '+field+' = {0}'.format(id))
    com()
    return print("all is ok")

def query(table):
    cur = db.connection.cursor()
    cur.execute("SELECT * FROM "+table)
    result = cur.fetchall()
    return result

def querySpecific(table,condition):
    cur().execute("SELECT * FROM "+table+" WHERE "+condition);
    result = cur().fetchall()
    return result

@cms.route('/')
def home():
    return render_template('cms_home.html')

@cms.route('/login')
def login():
    return render_template('cms_login.html')

@cms.route('/verano')
def verano():
    return render_template('cms_verano.html', verano = query("taller_verano"))

@cms.route('/verano/add',methods=['POST'])
def add_verano():
    if request.method == 'POST':
        id = 0
        nombre = request.form['nombre']
        portada = request.form['portada']
        dias = request.form['dias']
        horario = request.form['horario']
        edades = request.form['edades']
        cur().execute('INSERT INTO taller_verano (id,nombre,imagen,dias,horario,edades) VALUES (%s,%s,%s,%s,%s,%s)',(id,nombre,portada,dias,horario,edades))
        com()
        return redirect(url_for('cms.verano'))

@cms.route('/verano/update/<id>',methods=['POST','GET'])
def update_verano():
    return redirect(url_for('cms.verano'))

@cms.route('/verano/delete/<id>',methods=['POST','GET'])
def delete_verano(id):
    deleteRow(id,"taller_verano","id")
    return redirect(url_for('cms.verano'))

@cms.route('/permanente')
def permanente():
    return render_template('cms_permanente.html', permanente = query("taller_permanente"))

@cms.route('/permanente/add',methods=['POST'])
def add_permanente():
    if request.method == 'POST':
        id = 0
        nombre = request.form['nombre']
        portada = request.form['portada']
        dias = request.form['dias']
        horario = request.form['horario']
        edades = request.form['edades']
        cur().execute('INSERT INTO taller_permanente (id,nombre,imagen,dias,horario,edades) VALUES (%s,%s,%s,%s,%s,%s)',(id,nombre,portada,dias,horario,edades))
        com()
        return redirect(url_for('cms.permanente'))

@cms.route('/permanente/update/<id>',methods=['POST','GET'])
def update_permanente(id): 
    return redirect(url_for('cms.permanente'))

@cms.route('/permanente/delete/<id>',methods=['POST','GET'])
def delete_permanente(id):
    deleteRow(id,"taller_permanente","id")
    return redirect(url_for('cms.permenente'))

@cms.route('/galeria')
def galeria():
    return render_template('cms_galeria.html', galeria = query("galeria"))

@cms.route('/galeria/add',methods=['POST'])
def add_galeria():
    if request.method == 'POST':
        id = 0
        titulo = request.form['titulo']
        portada = request.form['portada']
        fecha = request.form['fecha']
        autor = request.form['autor']
        descripcion = request.form['descripcion']
        cur().execute('INSERT INTO galeria (id,titulo,imagen,fecha,autor,descripcion) VALUES (%s,%s,%s,%s,%s,%s)',(id,titulo,portada,fecha,autor,descripcion))
        com()
        return redirect(url_for('cms.galeria'))

@cms.route('galeria/update/<id>',methods=['POST','GET'])
def update_galeria():
    return redirect(url_for('cms.galeria'))

@cms.route('galeria/delete/<id>',methods=['POST','GET'])
def delete_galeria(id):
    deleteRow(id,"galeria","id")
    return redirect(url_for('cms.galeria'))

app/cms/templates/cms_galeria.html
{% extends "cms_layout.html" %}

{% block content %}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('cms.static',filename='css/style_cmsgaleria.css') }}">



<div class="general-container">
	<div class="title">
		<h3 id="prueba">GALERIA</h3>
	</div>
	<div class="form-container">
		<div class="title">
			<h3>Registro</h3>
		</div>
		<form action="{{url_for('cms.add_galeria')}}" method="POST">
			<h3>Titulo</h3>
			<input id="form-name" oninput="load()" type="text" name="titulo" placeholder="">
			<h3>Portada</h3>
			<input id="form-image" oninput="load()" type="text" name="portada" placeholder="">
			<h3>Fecha</h3>
			<input id="form-date" oninput="load()" type="date" name="fecha" placeholder="">
			<h3>Autor</h3>
			<input id="form-autor" oninput="load()" type="text" name="autor" placeholder="">
			<h3>Descripcion</h3>
			<textarea id="form-description" oninput="load()" name="descripcion" rows="9" cols="40"></textarea>
			<div class="bottom-buttons">
				<button type="submit"><b>Guardar</b></button>
			</div>
		</form>
	</div>
	<div class="preview-container">	
		<div class="title">
			<h3>Vista Previa</h3>
		</div>
	        <div class="article">	
			<div class="left-side">
		                <img id="preview-image"  src="">
			</div>
			<div class="right-side">
				<h2 id="preview-name"></h2>
				<p id="preview-description"></p>
				<div>
					<h5 id="preview-autor"></h5>
					<h5 id="preview-date"></h5>
				</div>
			</div>
		</div>
	</div>
	<div class="table-container">
		<div class="title">
			<h3>Tabla de contenidos</h3>
		</div>
		<table>
			<thead>
				<tr>
					<td>ID</td>
					<td>Titulo</td>
					<td>Imagen</td>
					<td>Fecha</td>
					<td>Autor</td>
					<td>Descripcion</td>
					<td colspan="2">Ajustes</td>
				</tr>
			</thead>
			<tbody>
				{% for ga in galeria %}
				<tr>
					<td>{{ga.0}}</td>
					<td>{{ga.1}}</td>
					<td>
						<div class="row">
							<div class="column">
								<img src="{{ga.2}}"/>
							</div>
						</div>
					</td>
					<td>{{ga.3}}</td>
					<td>{{ga.4}}</td>
					<!--<td>{{ga.5}}</td>-->
					<td>
						<a id="delete" href="/cms/galeria/delete/{{ ga.0 }}">Eliminar</a>
					</td>
					<td>
						<a id="update">Modificar</a>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
<script type="text/javascript">
	window.addEventListener('keydown',function(e){
		if(e.keyIdentifier=='U+000A'||e.keyIdentifier=='Enter'||e.keyCode==13){
			if(e.target.nodeName=='INPUT'&&e.target.type=='text'){
				e.preventDefault();
				return false;
			}
		}
	},true);
	function load() {
		  const a = document.getElementById("form-name").value;
		  document.getElementById("preview-name").innerHTML = a;

		  const b = document.getElementById("form-image").value;
		  document.getElementById("preview-image").src = b;

		  const c = document.getElementById("form-date").value;
		  document.getElementById("preview-date").innerHTML = c;

		  const d = document.getElementById("form-autor").value;
		  document.getElementById("preview-autor").innerHTML = d;

		  const e = document.getElementById("form-description").value;
		  document.getElementById("preview-description").innerHTML = e;
	}
</script>

{% endblock  %}

app/cms/templates/cms_home.html
{% extends "cms_layout.html" %}
{% block content %}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('cms.static',filename='css/style_cmshome.css') }}">
<div class="general-container">
	<div class="title">
		<h3 id="prueba">Bienvenido al panel de administración</h3>
	</div>

</div>
{% endblock %}

app/cms/templates/cms_layout.html
<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css"  href="{{ url_for('cms.static', filename='css/style_cmslayout.css') }}">
    <title>CentroCultural</title>
  </head>
  <body>
	  <header class="header">
	    <a  href="{{url_for('cms.home')}}" class="logo-header"><h1>Panel de <span>Administración</span></h1></a>
		<nav class="navbar">
			<ul>
				<li><a>Talleres</a>
					<ul>
						<li><a href="{{url_for('cms.verano')}}">Taller de verano</a></li>
						<li><a href="{{url_for('cms.permanente')}}">Taller permanente</a></li>
					</ul>
				</li>
				<li><a>Articulos</a></li>
				<li><a href="{{url_for('cms.galeria')}}">Galeria</a></li>
			</ul>
		</nav>
	  </header>
    <div class="container">
      {% block content%}
      {% endblock%}
   </div>
 
  </body>
 </html>

app/cms/templates/cms_login.html
<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css"  href="{{ url_for('cms.static', filename='css/style_cmslogin.css') }}">
    <script src="https://kit.fontawesome.com/f67351aa49.js" crossorigin="anonymous"></script>
    <title>CentroCultural</title>
  </head>
  <body>
    <div class="general-container">
	    <form class="form-container">
	    <div class="icon-container">
		    <i class="fa-solid fa-user" id="icon"></i>
	    </div>
	    <div class="inputs-container">
		<div><label id="title"><b>Inicio De Sesion</b></label></div>
	        <label for="fname"><b>Usuario</b></label>
		<input type="text" id="fname" name="fname" required>
		<label for="fname"><b>Constraseña</b></label>
		<input type="password" id="fname" name="fname" required>
	    </div>
		<button type="submit"><b>Ingresar</b></button>
	    </form>
   </div>
  </body>
</html>

app/cms/templates/cms_permanente.html
{% extends "cms_layout.html" %}

{% block content %}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('cms.static',filename='css/style_cmspermanente.css') }}">
<div class="general-container">
	<div class="title">
		<h3 id="prueba">TALLERES PERMANENTES</h3>
	</div>
	<div class="form-container">
		<div class="title">
			<h3>Registro</h3>
		</div>
		<form action="{{url_for('cms.add_permanente')}}" method="POST">
			<h3>Nombre</h3>
			<input id="form-name" oninput="load()" type="text" name="nombre" placeholder="">
			<h3>Portada</h3>
			<input id="form-image" oninput="load()" type="text" name="portada" placeholder="">
			<h3>Dias</h3>
			<textarea id="form-days" oninput="load()" name="dias" rows="2" cols="30"></textarea>
			<h3>Horario</h3>
			<textarea id="form-hours" oninput="load()" name="horario" rows="2" cols="30"></textarea>
			<h3>Edades</h3>
			<textarea id="form-ages" oninput="load()" name="edades" rows="2" cols="30"></textarea>
			<div class="bottom-buttons">
				<button type="submit"><b>Guardar</b></button>
			</div>
		</form>
	</div>
	<div class="preview-container">
		<div class="title">
			<h3>Vista Previa</h3>
		</div>
        	<div class="card">
        		<div class="face front">
          			<img id="preview-image"  src="" alt="">
          			<h3 id="preview-name"></h3>
        		</div>
        		<div class="face back">
          			<h3>Detalles</h3>
          			<p>
              				<div class="bot">Dias</div>
              				<div id="preview-days" ></div>
              				<div class="bot">Horario</div>
              				<div id="preview-hours"></div>
              				<div class="bot">Edades</div>
              				<div id="preview-ages"></div>
            			</p>
        		</div>
      		</div>
	</div>
	<div class="table-container">
		<div class="title">
			<h3>Tabla de contenidos</h3>
		</div>
		<table>
			<thead>
				<tr>
					<td>ID</td>
					<td>Nombre</td>
					<td>Dias</td>
					<td>Horario</td>
					<td>Edades</td>
					<td colspan="2">Ajustes</td>
				</tr>
			</thead>
			<tbody>
				{% for pe in permanente  %}
				<tr>
					<td>{{pe.0}}</td>
					<td>{{pe.1}}</td>
					<td>{{pe.3}}</td>
					<td>{{pe.4}}</td>
					<td>{{pe.5}}</td>
					<td>
						<a id="delete" href="/cms/permanente/delete/{{ pe.0 }}">Eliminar</a>
					</td>
					<td>
						<a id="update" href="/cms/permanente/update/{{ pe.0 }}">Modificar</a>
					</td>
				</tr>
				{%endfor%}
			</tbody>
		</table>
	</div>
</div>
<script type="text/javascript">
	window.addEventListener('keydown',function(e){
		if(e.keyIdentifier=='U+000A'||e.keyIdentifier=='Enter'||e.keyCode==13){
			if(e.target.nodeName=='INPUT'&&e.target.type=='text'){
				e.preventDefault();
				return false;
			}
		}
	},true);


	function load() {
		  const a = document.getElementById("form-name").value;
		  document.getElementById("preview-name").innerHTML = a;

		  const b = document.getElementById("form-image").value;
		  document.getElementById("preview-image").src = b;

		  const c = document.getElementById("form-days").value;
		  document.getElementById("preview-days").innerHTML = c;

		  const d = document.getElementById("form-hours").value;
		  document.getElementById("preview-hours").innerHTML = d;

		  const e = document.getElementById("form-ages").value;
		  document.getElementById("preview-ages").innerHTML = e;
	}





</script>

{% endblock %}

app/cms/templates/cms_verano.html
{% extends "cms_layout.html" %}
{% block content %}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('cms.static',filename='css/style_cmsverano.css') }}">
<div class="general-container">
	<div class="title">
		<h3 id="prueba">TALLERES DE VERANO</h3>
	</div>
	<div class="form-container">
		<div class="title">
			<h3>Registro</h3>
		</div>
		<form action="{{url_for('cms.add_verano')}}" method="POST">
			<h3>Nombre</h3>
			<input id="form-name" oninput="load()" type="text" name="nombre" placeholder="">
			<h3>Portada</h3>
			<input id="form-image" oninput="load()" type="text" name="portada" placeholder="">
			<h3>Dias</h3>
			<textarea id="form-days" oninput="load()" name="dias" rows="2" cols="30"></textarea>
			<h3>Horario</h3>
			<textarea id="form-hours" oninput="load()" name="horario" rows="2" cols="30"></textarea>
			<h3>Edades</h3>
			<textarea id="form-ages" oninput="load()" name="edades" rows="2" cols="30"></textarea>
			<div class="bottom-buttons">
				<button type="submit"><b>Guardar</b></button>
			</div>
		</form>
	</div>
	<div class="preview-container">
		<div class="title">
			<h3>Vista Previa</h3>
		</div>
        	<div class="card">
        		<div class="face front">
          			<img id="preview-image"  src="" alt="">
          			<h3 id="preview-name"></h3>
        		</div>
        		<div class="face back">
          			<h3>Detalles</h3>
          			<p>
              				<div class="bot">Dias</div>
              				<div id="preview-days" ></div>
              				<div class="bot">Horario</div>
              				<div id="preview-hours"></div>
              				<div class="bot">Edades</div>
              				<div id="preview-ages"></div>
            			</p>
        		</div>
      		</div>
	</div>
	<div class="table-container">
		<div class="title">
			<h3>Tabla de contenidos</h3>
		</div>
		<table id="content-table">
			<thead>
				<tr>
					<td>ID</td>
					<td>Nombre</td>
					<td>Dias</td>
					<td>Horario</td>
					<td>Edades</td>
					<td colspan="2">Ajustes</td>
				</tr>
			</thead>
			<tbody>
				{% for ve in verano  %}
				<tr>
					<td>{{ve.0}}</td>
					<td>{{ve.1}}</td>
					<td>{{ve.3}}</td>
					<td>{{ve.4}}</td>
					<td>{{ve.5}}</td>
					<td>
						<a id="delete" href="/cms/verano/delete/{{ ve.0 }}">Eliminar</a>
					</td>
					<td>
						<a id="update" href="">Modificar</a>
					</td>
				</tr>
				{%endfor%}
			</tbody>
		</table>
	</div>
</div>
<script type="text/javascript">
	window.addEventListener('keydown',function(e){
		if(e.keyIdentifier=='U+000A'||e.keyIdentifier=='Enter'||e.keyCode==13){
			if(e.target.nodeName=='INPUT'&&e.target.type=='text'){
				e.preventDefault();
				return false;
			}
		}
	},true);
	function load() {
		  const a = document.getElementById("form-name").value;
		  document.getElementById("preview-name").innerHTML = a;
		  const b = document.getElementById("form-image").value;
		  document.getElementById("preview-image").src = b;
		  const c = document.getElementById("form-days").value;
		  document.getElementById("preview-days").innerHTML = c;
		  const d = document.getElementById("form-hours").value;
		  document.getElementById("preview-hours").innerHTML = d;
		  const e = document.getElementById("form-ages").value;
		  document.getElementById("preview-ages").innerHTML = e;
	}
</script>
{% endblock %}