app/blog/__init__.py
from flask import Blueprint

blog = Blueprint('blog',__name__,
                 template_folder='templates',
                 static_folder='static')
from . import routes

app/blog/routes.py
from flask import render_template
from flask_mysqldb import MySQL
from . import blog
from app import db 


def query(table):
    cur = db.connection.cursor()
    cur.execute("SELECT * FROM "+table)
    result = cur.fetchall()
    return result

def queryLimit(table,position,amount):
    cur = db.connection.cursor()
    cur.execute("SELECT * FROM "+table+" LIMIT "+position+","+amount)
    result = cur.fetchall()
    return result

def queryCount(table,data='*'):
    cur = db.connection.cursor()
    if (data == '*'):
        cur.execute("SELECT COUNT(*) FROM "+table)
        tup = cur.fetchall()
    elif (data != '*' ):
        cur.execute("SELECT COUNT("+data+") FROM "+table)
        tup = cur.fetchall()

    string = str(tup)
    characters ="(,)' "
    for x in range(len(characters)):
            string = string.replace(characters[x],"")

    nstring = "".join(string)
    result = int(nstring)
    return result

def eventsbar():
    data = query('eventos')
    return data


@blog.route('/')
def home():
    #data = queryCount('taller_verano')
    return render_template('home.html',eventos = eventsbar())

@blog.route('/talleres-verano')
def verano():
    return render_template('verano.html',verano = query('taller_verano'),eventos = eventsbar())

@blog.route('/talleres-permanentes')
def permanente():
    return render_template('permanentes.html',permanentes = query('taller_permanente'),eventos = eventsbar())

@blog.route('/galeria')
def galeria():
    medio = round(queryCount('galeria')/3)
    data1 = queryLimit("galeria",str(0),str(medio))
    data2 = queryLimit("galeria",str(medio),str(medio))
    data3 = queryLimit("galeria",str(medio*2),str(queryCount('galeria')-(medio*2)))
    return render_template('galeria.html',eventos = eventsbar(),col1 = data1,col2 = data2,col3 = data3)

@blog.route('/galeria/<title>')
def imagen(title):
    return render_template('imagen.html',eventos = eventsbar(),galeria = query('galeria'),filtro = title)

@blog.route('/calendario')
def calendario():
    return render_template('calendario.html', eventos = eventsbar())

@blog.route('/articulos')
def articulos():
    return render_template('articulos.html',articulos = query('articulos'), eventos = eventsbar())

@blog.route('/articulo/<title>')
def articulo(title):
    return render_template('articulo.html',eventos = eventsbar(), articulo = query('articulos'),filtro = title)

@blog.route('/articulos/categoria/<tag>')
def categoria(tag):
    return render_template('categoria.html',articulos = query('articulos'),eventos = eventsbar(),filtro = tag)

app/blog/templates/articulo.html
{% extends "layout.html" %}

{% block content %}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('blog.static',filename='css/style_articulo.css') }}">
<div class="general-container">
	{% for a in articulo %}
	{% if a.1 == filtro %}
  <article class="article">
    <div class="title">
    <h1>{{ a.1 }}</h1>
    </div>
    <div class="img" style="background: url({{ a.2 }}) no-repeat center center fixed;"></div>
    <div class="info">
      <div class="date">{{ a.3 }}</div>
      <div class="divisor"></div>
      <div class="tag">{{ a.4 }}</div>
    </div>
   
    <div class="body">{{ a.5 }}</div>
    
  </article>
  	 {% endif %}
	 {% endfor  %}
</div>
{% endblock%}

app/blog/templates/articulos.html
{% extends "layout.html" %}
{% block content %}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('blog.static',filename='css/style_articulos.css') }}">
<div class="general-container">
<div class="tag-list">
	<div>
		<div class="list-element"><a href="/blog/articulos/categoria/Arte" class="element" style="background:#C0392B;">Arte</a></div>
	<div class="list-element"><a href="/blog/articulos/categoria/Cine" class="element" style="background:#9B59B6;">Cine</a></div>
	<div class="list-element"><a href="/blog/articulos/categoria/Cultura" class="element" style="background:#2980B9">Cultura</a></div>
	<div class="list-element"><a href="/blog/articulos/categoria/Historia" class="element" style="background:#1ABC9C">Historia</a></div>
	<div class="list-element"><a href="/blog/articulos/categoria/Literatura" class="element" style="background:#F900F2">Literatura</a></div>
	</div>
	<div>        
	<div class="list-element"><a href="/blog/articulos/categoria/Musica" class="element" style="background:#F1C40F">Musica</a></div>
	<div class="list-element"><a href="/blog/articulos/categoria/Eventos" class="element" style="background:#E67E22">Eventos</a></div>
	<div class="list-element"><a href="/blog/articulos/categoria/Otros" class="element" style="background:#34495E">Otros</a></div>
	</div>
</div>
  <div class="article-container">
    {% for ar in  articulos  %}
  <div class="blog-entry">
    <img class="blog-img" src="{{ ar.2 }}" alt="">
    <div class="content-date"><div class="date">{{ ar.3 }}</div></div>
    <div class="blog-content">
      <div class="content-title"><h1>{{ ar.1 }}</h1></div>

      <div class="content-tag"  ><a href="/blog/articulos/categoria/{{ ar.4 }}">{{ ar.4 }}</a></div>
      <span class="content-text">{{ ar.5 }}</span>
        <a class="content-button" href="/blog/articulo/{{ ar.1 }}">Leer mas</a>
    </div>
  </div>
 
  {% endfor %}

 <script>
	window.onload = function setColor(){
			  const elements = document.getElementsByClassName('content-tag')
			 for(var i = 0;i < elements.length;i++){
			  if(elements[i].textContent == "Arte"){elements[i].style.background="#C0392B";}
			  if(elements[i].textContent == "Cine"){elements[i].style.background="#9B59B6";}
			  if(elements[i].textContent == "Cultura"){elements[i].style.background="#2980B9";}
			  if(elements[i].textContent == "Historia"){elements[i].style.background="#1ABC9C";}
			  if(elements[i].textContent == "Literatura"){elements[i].style.background="#F900F2";}
			  if(elements[i].textContent == "Musica"){elements[i].style.background="#F1C40F";}
			  if(elements[i].textContent == "Eventos"){elements[i].style.background="#E67E22";}
			  if(elements[i].textContent == "Otros"){elements[i].style.background="#34495E";}
				  }
			 
		 };
 </script> 
    </div>
</div>

{% endblock%}

app/blog/templates/calendario.html
{% extends "layout.html" %}

{% block content %}
<link rel="stylesheet" href="static/css/style_calendario.css">
<div class="general-container">
  <div class="calendar-container">
  <table>
    <tr>
      <th class="month" colspan="7"><h2>Julio</h2></th>
    </tr>
    <tr>
      <td class="day"><span><h4>Domingo</h4></span></td>
      <td class="day"><span><h4>Lunes</h4></span></td>
      <td class="day"><span><h4>Marnes</h4></span></td>
      <td class="day"><span><h4>Miercoles</h4></span></td>
      <td class="day"><span><h4>Jueves</h4></span></td>
      <td class="day"><span><h4>Viernes</h4></span></td>
      <td class="day"><span><h4>Sabado</h4></span></td>
    </tr>
    <tr>
      <td>
        <div class="card">
        <div class="face front">
          <h1></h1>
        </div>
        <div class="face back">
          <span><h4></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>1</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>2</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>3</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>4</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>5</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>6</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="card">
        <div class="face front">
          <h1>7</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>8</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>9</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>10</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>12</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>13</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>14</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="card">
        <div class="face front">
          <h1>15</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>16</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>17</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>18</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>19</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>20</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>21</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="card">
        <div class="face front">
          <h1>22</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>23</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>24</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>25</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>26</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>27</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>28</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="card">
        <div class="face front">
          <h1>29</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>30</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1>31</h1>
        </div>
        <div class="face back">
          <span><h4><a href="#">Sin eventos</a></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1></h1>
        </div>
        <div class="face back">
          <span><h4></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1></h1>
        </div>
        <div class="face back">
          <span><h4></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1></h1>
        </div>
        <div class="face back">
          <span><h4></h4></span>
        </div>
        </div>
      </td>
      <td>
        <div class="card">
        <div class="face front">
          <h1></h1>
        </div>
        <div class="face back">
          <span><h4></h4></span>
        </div>
        </div>
      </td>
    </tr>
    <div class="events-container">
      <div class="head-events">
        <h2>Eventos programados</h2>
      </div>
      <div class="body-events">
        <h3>Sin eventos...</h3>
      </div>
    </div>
    <div class="times-container">
      <div class="head-times">
        <h2>Horarios disponibles</h2>
      </div>
      <div class="body-times">
        <h3>Sin horarios disponibles...</h3>
      </div>
    </div>
  </table>

  </div>

</div>
{% endblock%}

app/blog/templates/categoria.html
{% extends "layout.html" %}
{% block content %}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('blog.static',filename='css/style_categoria.css') }}">
<div class="general-container">
<div class="tag-list">
	<div>
	<div class="list-element"><a href="/blog/articulos/categoria/Arte" class="element" style="background:#C0392B;">Arte</a></div>
	<div class="list-element"><a href="/blog/articulos/categoria/Cine" class="element" style="background:#9B59B6;">Cine</a></div>
	<div class="list-element"><a href="/blog/articulos/categoria/Cultura" class="element" style="background:#2980B9">Cultura</a></div>
	<div class="list-element"><a href="/blog/articulos/categoria/Historia" class="element" style="background:#1ABC9C">Historia</a></div>
	<div class="list-element"><a href="/blog/articulos/categoria/Literatura" class="element" style="background:#F900F2">Literatura</a></div>
	</div>
	<div>        
	<div class="list-element"><a href="/blog/articulos/categoria/Musica" class="element" style="background:#F1C40F">Musica</a></div>
	<div class="list-element"><a href="/blog/articulos/categoria/Eventos" class="element" style="background:#E67E22">Eventos</a></div>
	<div class="list-element"><a href="/blog/articulos/categoria/Otros" class="element" style="background:#34495E">Otros</a></div>
	</div>
</div>
  <div class="article-container">
    {% for ar in  articulos  %}
    {% if ar.4 == filtro %}
  <div class="blog-entry">
    <img class="blog-img" src="{{ ar.2 }}" alt="">
    <div class="content-date"><div class="date">{{ ar.3 }}</div></div>
    <div class="blog-content">
      <div class="content-title"><h1>{{ ar.1 }}</h1></div>
      <div class="content-tag"><a href="/blog/articulos/categoria/{{ ar.4 }}">{{ ar.4 }}</a></div>
      <span class="content-text">{{ ar.5 }}</span>
        <a class="content-button" href="/blog/articulo/{{ ar.1 }}">Leer mas</a>
    </div>
  </div>
  {% endif %}
  {% endfor %}
 <script>
	window.onload = function setColor(){
			  const elements = document.getElementsByClassName('content-tag')
			 for(var i = 0;i < elements.length;i++){
			  if(elements[i].textContent == "Arte"){elements[i].style.background="#C0392B";}
			  if(elements[i].textContent == "Cine"){elements[i].style.background="#9B59B6";}
			  if(elements[i].textContent == "Cultura"){elements[i].style.background="#2980B9";}
			  if(elements[i].textContent == "Historia"){elements[i].style.background="#1ABC9C";}
			  if(elements[i].textContent == "Literatura"){elements[i].style.background="#F900F2";}
			  if(elements[i].textContent == "Musica"){elements[i].style.background="#F1C40F";}
			  if(elements[i].textContent == "Eventos"){elements[i].style.background="#E67E22";}
			  if(elements[i].textContent == "Otros"){elements[i].style.background="#34495E";}
				  }
			 
		 };
 </script> 
    </div>
</div>
{% endblock%}

app/blog/templates/galeria.html
{% extends "layout.html" %}

{% block content %}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('blog.static',filename='css/style_galeria.css') }}">
<div class="general-container">
	<div class="title">
	     <h1>Galeria</h1>
	</div>
	<div class="row">
		<div class="column">
	{% for ga1 in col1 %}
	<a href="/blog/galeria/{{ ga1.1 }}"><img  src="{{ ga1.2 }}"/></a>
	{%endfor%}
		</div>		
		<div class="column">
	{% for ga2 in col2 %}
	<a href="/blog/galeria/{{ ga2.1 }}"><img  src="{{ ga2.2 }}"/></a>
	{%endfor%}
		</div>	
		<div class="column">
	{% for ga3 in col3 %}
	<a href="/blog/galeria/{{ ga3.1 }}"><img  src="{{ ga3.2 }}"/></a>
	{%endfor%}
		</div>	
	</div>
</div>
{% endblock%}

app/blog/templates/home.html
{% extends "layout.html" %}

{% block content %}

    <link rel="stylesheet" href="{{url_for('blog.static',filename='css/style_home.css')}}">
<div class="general-container">
  <!---->
  <div class="container">
    <h1 class="title">Desarrolla tus habilidades</h1>
    <h1 class="title title-large">Desarrolla tus habilidades</h1>
    <div id="img-1" class="img-container">
	    <img class="img" src="static/images/card1.jpg">
    </div>

    <div class="img-container second-animation">
      <img class="img" src="static/images/card2.jpg">
    </div>

    <div class="img-container third-animation">
      <img class="img" src="static/images/card3.jpg">
    </div>

    <div class="img-container fourth-animation">
      <img class="img nba" src="static/images/card4.jpg">
    </div>

    <div class="img-container fifth-animation">
      <img class="img" src="static/images/card5.jpg">
    </div>

    <div id="img-6" class="img-container sixth-animation">
      <img class="img" src="static/images/card6.jpg">
    </div>

    <div id="img-7" class="img-container seventh-animation">
      <img class="img" src="static/images/card7.jpg">
    </div>
  </div>
  <div class="banner-gmaps">
    <h2>Encuentranos en</h2>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3820.488278132336!2d-93.10819288598235!3d16.752365725219303!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85ecd88665921a1d%3A0x3ea0b7329fb7ae15!2sCentro%20Cultural%20de%20Chiapas%20%22Jaime%20Sabines%22!5e0!3m2!1ses!2smx!4v1657220573312!5m2!1ses!2smx" width="1346" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
  </div>

</div>
{% endblock%}

app/blog/templates/imagen.html
{% extends "layout.html" %}
{% block content %}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('blog.static',filename='css/style_imagen.css') }}">
<div class="general-container">
	{% for ga in galeria  %}
	{% if ga.1 == filtro %}
	<div class="article">
		<div class="left-side">
			<img src="{{ga.2}}">
		</div>
		<div class="right-side">
			<h2>{{ga.1}}</h2>
			<p>{{ga.5}}</p>
			<div>
				<h5>{{ga.4}}</h5>
				<h5>{{ga.3}}</h5>
			</div>
		</div>
	</div>
  	{% endif %}
	{% endfor  %}
	
</div>
{% endblock %}

app/blog/templates/layout.html
<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css"  href="{{ url_for('blog.static', filename='css/style_layout.css') }}">
    <title>CentroCultural</title>
  </head>
  <body>
    <header class="header">
	    <a  href="{{url_for('blog.home')}}" class="logo-header"><h1>Centro<span>Cultural</span></h1></a>
          <div class="events-bar">
            <div class="events-fondo"></div>
            <div class="events-text">
              <p class="events-title">Proximos eventos</p>
              {% for evn in  eventos  %}
	      <p class="text">{{ evn.1+" " }}{{evn.3}}</p>
              {% endfor %}
            </div>
          </div>
          <nav class="navbar">
		  
            <ul>
              <li><a href="#">Talleres</a>
                <ul>
			<li><a href="{{url_for('blog.verano')}}">Verano</a></li>
			<li><a href="{{url_for('blog.permanente')}}">Permamentes</a></li>
                </ul>
              </li>
	      <li><a href="{{url_for('blog.articulos')}}">Articulos</a>
	      </li>
	      <li><a href="{{url_for('blog.calendario')}}">Calendario</a></li>
	      <li><a href="{{url_for('blog.galeria')}}">Galeria</a></li>
	      
            </ul>
	    	  
          </nav>
    </header>
    <div class="container">
      {% block content%}
    	{% endblock%}
   </div>
  </body>
</html>

app/blog/templates/permanentes.html
{% extends "layout.html" %}

{% block content %}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('blog.static',filename='css/style_permanentes.css') }}">
<div class="general-container">
  <div class="title">
    <h1>Talleres Permanentes</h1>
  </div>
  <div class="table">
        {% for pe in  permanentes  %}

          <div class="card">
          <div class="face front">
            <img src="{{ pe.2 }}" alt="">
            <h3>{{ pe.1 }}</h3>
          </div>
          <div class="face back">
            <h3>Detalles</h3>
            <p>
                <div class="bot">Dias</div>
                <div>{{ pe.3 }}</div>
                <div class="bot">Horario</div>
                <div>{{ pe.4 }}</div>
                <div class="bot">Edades</div>
                <div>{{ pe.5 }}</div>
              </p>
          </div>
        </div>

        {% endfor %}
  </div>
</div>
{% endblock%}

app/blog/templates/verano.html
{% extends "layout.html" %}

{% block content %}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('blog.static',filename='css/style_verano.css') }}">
<div class="general-container">
  <div class="title">
    <h1>Talleres De Verano</h1>
  </div>

<div class="table">
      {% for ve in  verano %}

        <div class="card">
        <div class="face front">
          <img src="{{ ve.2 }}" alt="">
          <h3>{{ ve.1 }}</h3>
        </div>
        <div class="face back">
          <h3>Detalles</h3>
          <p>
              <div class="bot">Dias</div>
              <div>{{ ve.3 }}</div>
              <div class="bot">Horario</div>
              <div>{{ ve.4 }}</div>
              <div class="bot">Edades</div>
              <div>{{ ve.5 }}</div>
            </p>
        </div>
      </div>

      {% endfor %}
</div>

</div>


{% endblock%}